### ISSUE TITLE
Cocoapod Support

### ISSUE THREAD

**Issue by mattnydam** [martinezdelariva/MRCircularProgressView#2]
It would be awesome if this was available as a cocoa pod!

Handy links:
- [NSScreencast - Creating a cocoapod](http://nsscreencast.com/episodes/28-creating-a-cocoapod)
- [Good ol' StackOverflow](http://stackoverflow.com/questions/18107768/how-do-you-convert-an-xcode-project-into-a-cocoapod)

**Comment by martinezdelariva** [comment]
Created  pull request to cocoapods/specs
