### ISSUE TITLE
Method reset

### ISSUE THREAD

**Issue by paliburger** [martinezdelariva/MRCircularProgressView#4]
Hola, hay algún método para hacer un reset, verás. Necesito llevar un el progreso de actividades de manera secuencial. Al pasar de una actividad a otra por el hecho de que el usuario puede saltar varias tareas y posicionarse en una más adelante. Al poner el progreso en 0.0, no me esta limpiando la vista, para que yo pueda hacer un nuevo setup del CirculaProgressView con nuevos tiempos en la duración.

**Comment by martinezdelariva** [comment]
Actually reset method doesn't exist. I want to create it instead to set the progress 0.0 manually.
Anyway I can't reproduce your case, if you set progress to 0.0 it should work.

---

No hay ningún método para hacer reset, lo introduciré en breve.
De todas maneras no puedo reproducir tu caso. ¿Cuando pones el progreso en 0.0 se queda el progreso en 0.0.?
